{
 "title": "QuickNotes",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Latency proxy (requests/s, NOT seconds)",
   "type": "timeseries",
   "gridPos": { "w": 12, "x": 0, "h": 8, "y": 0.0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(quicknotes_http_requests_total{job=\"quicknotes\"}[5m]))"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "w": 12, "x": 12, "h": 8, "y": 0.0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(quicknotes_http_requests_total{job=\"quicknotes\"}[5m]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "w": 12, "x": 0, "h": 8, "y": 8.0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(quicknotes_http_responses_by_code_total{job=\"quicknotes\",code=~\"4..|5..\"}[5m])) / sum(rate(quicknotes_http_requests_total{job=\"quicknotes\"}[5m]))"
    }
   ]
  },
  {
   "title": "Saturation (stored notes)",
   "type": "timeseries",
   "gridPos": { "w": 12, "x": 12, "h": 8, "y": 8.0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "quicknotes_notes_total{job=\"quicknotes\"}"
    }
   ]
  }
 ]
}